export const SET_POSITION="SET_POSITION";

//export const SET_SINGER_NAME="SET_SINGER_NAME";

export const SET_SHOWPOSITION="SET_SHOWPOSITION";
export const SET_CITY="SET_CITY";
export const SET_ORDERADDRESS="SET_ORDERADDRESS";